name: ApiVideoUploader
targets:
  ApiVideoUploader:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [Sources]
    info:
      path: ./Info.plist
      version: 0.1.4
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
    - carthage: Alamofire
